// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcOgoIjiCAcqlzvWiAFdCzkWdESUt1aCw',
    appId: '1:836051518708:web:7ce46546bb5bfe20424aa1',
    messagingSenderId: '836051518708',
    projectId: 'mynotes-ronak',
    authDomain: 'mynotes-ronak.firebaseapp.com',
    storageBucket: 'mynotes-ronak.firebasestorage.app',
    measurementId: 'G-68B6YTGWWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-FYbyJHDLn8Lr1jeXdztUCIeAj9yKIo',
    appId: '1:836051518708:android:4e315ee56b4513e7424aa1',
    messagingSenderId: '836051518708',
    projectId: 'mynotes-ronak',
    storageBucket: 'mynotes-ronak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD47S7XXULFVlUywgLIO1F8q7UieOH2Td8',
    appId: '1:836051518708:ios:2a97eeb5bc10770a424aa1',
    messagingSenderId: '836051518708',
    projectId: 'mynotes-ronak',
    storageBucket: 'mynotes-ronak.firebasestorage.app',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD47S7XXULFVlUywgLIO1F8q7UieOH2Td8',
    appId: '1:836051518708:ios:2a97eeb5bc10770a424aa1',
    messagingSenderId: '836051518708',
    projectId: 'mynotes-ronak',
    storageBucket: 'mynotes-ronak.firebasestorage.app',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
